In [1]:
import pandas as pd
import json
import re
from html import unescape

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
with open('fipi_exported_katex.json', 'r', encoding='utf-8') as f:
    fipi_data = json.load(f)

with open('all_variants_all_years.json', 'r', encoding='utf-8') as f:
    real_data = json.load(f)

In [4]:

def clean_html(text):
    if text is None:
        return None
    text = str(text)
    text = unescape(text)
    text = re.sub(r'<[^>]+>', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [5]:

fipi_rows = []

for task in fipi_data:

    problem_src = task.get('problem_katex') or task.get('problem')

    fipi_rows.append({
        'dataset_source': 'fipi',
        'task_id': task.get('id'),
        'task_number': task.get('task_number'),
        'question_text': clean_html(task.get('question')),
        'problem_text': clean_html(problem_src),
        'question_raw': task.get('question'),
        'problem_raw': problem_src,
        'codifier': task.get('codifier'),
        'answer_type': task.get('answer_type'),
        'answer': task.get('answer')
    })

df_fipi = pd.DataFrame(fipi_rows)

In [6]:
df_fipi.head()

,dataset_source,task_id,task_number,question_text,problem_text,question_raw,problem_raw,codifier,answer_type,answer
0,fipi,40B442,2,Даны векторы a → ( 25; 0 ) и b → ( 1; −5 ). На...,Даны векторы \overrightarrow{a} ( 25; 0 ) и \o...,Даны векторы a &#x2192; ( 25;&#x2009;0 ) и b ...,"<p class=""MsoNormal"">Даны векторы <span class=...",[7.5 Координаты и векторы],Краткий ответ,29
1,fipi,4CBD4E,6,Найдите корень уравнения ( 1 7 ) x + 4 =49 .; ;,Найдите корень уравнения ( 1 7 ) x + 4 = 49 .,Найдите корень уравнения ( 1 7 ) x&#x2009;+&#x...,"<p class=""MsoNormal"">Найдите корень уравнения ...","[2.1 Целые и дробно-рациональные уравнения, 2....",Краткий ответ,-6
2,fipi,FDA042,13,а) Решите уравнение 9 sin2x − 3 2 2 sinx 11sin...,а) Решите уравнение 9 sin 2 x − 3 2 2 sin x 11...,а) Решите уравнение 9 sin2x &#x2212; 3 2 2 sin...,"<p class=""MsoNormal"">а) Решите уравнение <m:ma...","[2.3 Тригонометрические уравнения, 2.4 Показат...",Развернутый ответ,
3,fipi,0A394E,2,Даны векторы a → ( − 13 ; 4 ) и b → ( − 6 ; 1 ...,Даны векторы a → ( − 13 ; 4 ) и b → ( − 6 ; 1 ...,Даны векторы a &#x2192; ( &#x2212;&#x2009;13&#...,"<p class=""MsoNormal"">Даны векторы <m:math> <m:...",[7.5 Координаты и векторы],Краткий ответ,82
4,fipi,75244F,4,Фабрика выпускает сумки. В среднем 4 сумки из ...,Фабрика выпускает сумки. В среднем 4 сумки из ...,Фабрика выпускает сумки. В среднем 4 сумки из ...,"<p class=""MsoNormal""><span>Фабрика выпускает с...",[6.2 Вероятность],Краткий ответ,0.92

In [7]:

real_rows = []

for year_block, variants in real_data.items():
    for variant in variants:
        variant_title = variant.get('title')
        variant_url = variant.get('url')

        for task in variant.get('tasks', []):
            real_rows.append({
                'dataset_source': 'real_exam',
                'year_block': year_block,
                'variant_title': variant_title,
                'variant_url': variant_url,
                'variant_id': task.get('source_id') or variant_title,

                'task_id': task.get('id'),
                'task_number': task.get('task_number'),

                'question_raw': task.get('question'),
                'problem_raw': task.get('problem'),

                'question_text': clean_html(task.get('question')),
                'problem_text': clean_html(task.get('problem')),

                'codifier': task.get('codifier'),
                'answer_type': task.get('answer_type'),
                'answer': task.get('answer')
            })

df_real = pd.DataFrame(real_rows)

In [8]:
df_real.head()

,dataset_source,year_block,variant_title,variant_url,variant_id,task_id,task_number,question_raw,problem_raw,question_text,problem_text,codifier,answer_type,answer
0,real_exam,2024-2025,ЕГЭ по математике 28.03.2025. Досрочная волна....,https://math-ege.sdamgia.ru/test?id=84138204,ЕГЭ по математике 28.03.2025. Досрочная волна....,680500,1,Площадь параллелограмма ABCD равна 28. Точка E...,"<div align=""justify"" class=""pbody"" id=""body265...",Площадь параллелограмма ABCD равна 28. Точка E...,Пло­щадь па­рал­ле­ло­грам­ма ABCD равна 28. Т...,[Планиметрия. Параллелограммы],Краткий ответ,
1,real_exam,2024-2025,ЕГЭ по математике 28.03.2025. Досрочная волна....,https://math-ege.sdamgia.ru/test?id=84138204,ЕГЭ по математике 28.03.2025. Досрочная волна....,680501,2,Даны векторы Найдите скалярное произведение ве...,"<div align=""justify"" class=""pbody"" id=""body265...",Даны векторы Найдите скалярное произведение ве...,Даны век­то­ры Най­ди­те ска­ляр­ное про­из­ве...,[Кодификатор ФИПИ/Решу ЕГЭ: 5.6.6 Координаты в...,Краткий ответ,
2,real_exam,2024-2025,ЕГЭ по математике 28.03.2025. Досрочная волна....,https://math-ege.sdamgia.ru/test?id=84138204,ЕГЭ по математике 28.03.2025. Досрочная волна....,680502,3,Прямоугольный параллелепипед описан около цили...,"<div align=""justify"" class=""pbody"" id=""body265...",Прямоугольный параллелепипед описан около цили...,Пря­мо­уголь­ный па­рал­ле­ле­пи­пед опи­сан о...,[Стереометрия. Комбинации тел],Краткий ответ,
3,real_exam,2024-2025,ЕГЭ по математике 28.03.2025. Досрочная волна....,https://math-ege.sdamgia.ru/test?id=84138204,ЕГЭ по математике 28.03.2025. Досрочная волна....,680503,4,Перед началом волейбольного матча капитаны ком...,"<div align=""justify"" class=""pbody"" id=""body265...",Перед началом волейбольного матча капитаны ком...,Перед на­ча­лом во­лей­боль­но­го матча ка­пи­...,[Начала теории вероятностей. Классическое опре...,Краткий ответ,
4,real_exam,2024-2025,ЕГЭ по математике 28.03.2025. Досрочная волна....,https://math-ege.sdamgia.ru/test?id=84138204,ЕГЭ по математике 28.03.2025. Досрочная волна....,680504,5,Помещение освещается фонарём с двумя лампами. ...,"<div align=""justify"" class=""pbody"" id=""body265...",Помещение освещается фонарём с двумя лампами. ...,По­ме­ще­ние осве­ща­ет­ся фонарём с двумя лам...,[Вероятности сложных событий. Теоремы о вероят...,Краткий ответ,

In [9]:
df_all = pd.concat([df_fipi, df_real], ignore_index=True)

In [10]:
df_all.head()

,dataset_source,task_id,task_number,question_text,problem_text,question_raw,problem_raw,codifier,answer_type,answer,year_block,variant_title,variant_url,variant_id
0,fipi,40B442,2,Даны векторы a → ( 25; 0 ) и b → ( 1; −5 ). На...,Даны векторы \overrightarrow{a} ( 25; 0 ) и \o...,Даны векторы a &#x2192; ( 25;&#x2009;0 ) и b ...,"<p class=""MsoNormal"">Даны векторы <span class=...",[7.5 Координаты и векторы],Краткий ответ,29,NaN,NaN,NaN,NaN
1,fipi,4CBD4E,6,Найдите корень уравнения ( 1 7 ) x + 4 =49 .; ;,Найдите корень уравнения ( 1 7 ) x + 4 = 49 .,Найдите корень уравнения ( 1 7 ) x&#x2009;+&#x...,"<p class=""MsoNormal"">Найдите корень уравнения ...","[2.1 Целые и дробно-рациональные уравнения, 2....",Краткий ответ,-6,NaN,NaN,NaN,NaN
2,fipi,FDA042,13,а) Решите уравнение 9 sin2x − 3 2 2 sinx 11sin...,а) Решите уравнение 9 sin 2 x − 3 2 2 sin x 11...,а) Решите уравнение 9 sin2x &#x2212; 3 2 2 sin...,"<p class=""MsoNormal"">а) Решите уравнение <m:ma...","[2.3 Тригонометрические уравнения, 2.4 Показат...",Развернутый ответ,,NaN,NaN,NaN,NaN
3,fipi,0A394E,2,Даны векторы a → ( − 13 ; 4 ) и b → ( − 6 ; 1 ...,Даны векторы a → ( − 13 ; 4 ) и b → ( − 6 ; 1 ...,Даны векторы a &#x2192; ( &#x2212;&#x2009;13&#...,"<p class=""MsoNormal"">Даны векторы <m:math> <m:...",[7.5 Координаты и векторы],Краткий ответ,82,NaN,NaN,NaN,NaN
4,fipi,75244F,4,Фабрика выпускает сумки. В среднем 4 сумки из ...,Фабрика выпускает сумки. В среднем 4 сумки из ...,Фабрика выпускает сумки. В среднем 4 сумки из ...,"<p class=""MsoNormal""><span>Фабрика выпускает с...",[6.2 Вероятность],Краткий ответ,0.92,NaN,NaN,NaN,NaN

In [11]:
df_all.isna().sum()

dataset_source      0
task_id             0
task_number         0
question_text       0
problem_text        0
question_raw        0
problem_raw         0
codifier            0
answer_type         0
answer              0
year_block        978
variant_title     978
variant_url       978
variant_id        978
dtype: int64

In [12]:
df_all['answer_type'] = df_all['answer_type'].replace({
    'Развернутый ответ': 'Развёрнутый ответ'
})
df_all['answer_type'].value_counts()

answer_type
Развёрнутый ответ    2544
Краткий ответ        1631
Name: count, dtype: int64

In [13]:
df_all.to_csv('tasks.csv', index=False)

In [2]:
import pandas as pd
df_all = pd.read_csv('tasks.csv')
df_oge = pd.read_json('oge_math_tasks.json')

In [ ]:
# df_oge['answer_empty'] = df_oge['answer_options'].apply(lambda x: len(x) == 0 if isinstance(x, list) else True)
# df_oge['image_empty'] = df_oge['images'].apply(lambda x: len(x) == 0 if isinstance(x, list) else True)

In [9]:
df_oge.head()

,task_id,guid,oge_number,original_page,text,answer_options,images,correct_answer,answer_empty,image_empty
0,45B944,00048BBEB81FA06F4CD9D713B8A500DE,NaN,1,Какое из следующих утверждений является истинн...,[1) Площадь квадрата равна произведению двух е...,[],NaN,False,True
1,426640,002D6D7DB3E2A89A4205399B29F533B2,NaN,1,Какое из следующих утверждений является истинн...,"[1) Все углы ромба равны., 2) Если стороны одн...",[],NaN,False,True
2,494C47,0030BAF3C700977544917A787D27C7A9,NaN,1,Мощность постоянного тока (в ваттах) вычисляет...,[],[],NaN,True,True
3,46334D,007EDE787C96ABB34E1EBE254F5468CA,NaN,1,"У бабушки 20 чашек: 10 с красными цветами, ост...",[],[],NaN,True,True
4,4F5745,0088136AD101954045CAED9DA7A77650,NaN,1,Один из углов прямоугольной трапеции равен 64 ...,[],[https://oge.fipi.ru/docs/DE0E276E497AB3784C3F...,NaN,True,False

In [11]:
df_oge['image_empty'].value_counts()

image_empty
True     2343
False    1541
Name: count, dtype: int64

In [12]:
df_all.head()

,dataset_source,task_id,task_number,question_text,problem_text,question_raw,problem_raw,codifier,answer_type,answer,year_block,variant_title,variant_url,variant_id
0,fipi,40B442,2,Даны векторы a → ( 25; 0 ) и b → ( 1; −5 ). На...,Даны векторы \overrightarrow{a} ( 25; 0 ) и \o...,Даны векторы a &#x2192; ( 25;&#x2009;0 ) и b ...,"<p class=""MsoNormal"">Даны векторы <span class=...",['7.5 Координаты и векторы'],Краткий ответ,29,NaN,NaN,NaN,NaN
1,fipi,4CBD4E,6,Найдите корень уравнения ( 1 7 ) x + 4 =49 .; ;,Найдите корень уравнения ( 1 7 ) x + 4 = 49 .,Найдите корень уравнения ( 1 7 ) x&#x2009;+&#x...,"<p class=""MsoNormal"">Найдите корень уравнения ...","['2.1 Целые и дробно-рациональные уравнения', ...",Краткий ответ,-6,NaN,NaN,NaN,NaN
2,fipi,FDA042,13,а) Решите уравнение 9 sin2x − 3 2 2 sinx 11sin...,а) Решите уравнение 9 sin 2 x − 3 2 2 sin x 11...,а) Решите уравнение 9 sin2x &#x2212; 3 2 2 sin...,"<p class=""MsoNormal"">а) Решите уравнение <m:ma...","['2.3 Тригонометрические уравнения', '2.4 Пока...",Развёрнутый ответ,NaN,NaN,NaN,NaN,NaN
3,fipi,0A394E,2,Даны векторы a → ( − 13 ; 4 ) и b → ( − 6 ; 1 ...,Даны векторы a → ( − 13 ; 4 ) и b → ( − 6 ; 1 ...,Даны векторы a &#x2192; ( &#x2212;&#x2009;13&#...,"<p class=""MsoNormal"">Даны векторы <m:math> <m:...",['7.5 Координаты и векторы'],Краткий ответ,82,NaN,NaN,NaN,NaN
4,fipi,75244F,4,Фабрика выпускает сумки. В среднем 4 сумки из ...,Фабрика выпускает сумки. В среднем 4 сумки из ...,Фабрика выпускает сумки. В среднем 4 сумки из ...,"<p class=""MsoNormal""><span>Фабрика выпускает с...",['6.2 Вероятность'],Краткий ответ,0.92,NaN,NaN,NaN,NaN

In [3]:


oge_rows = []

for _, task in df_oge.iterrows():
    
    text = task.get('text')
    
    oge_rows.append({
        'dataset_source': 'oge_fipi',
        'task_id': task.get('task_id'),

        'question': text,
        'problem': text,

        'question_raw': text,
        'problem_raw': text,

        'answer_options': task.get('answer_options'),

        'answer': task.get('correct_answer'),

        
    })

df_oge_final = pd.DataFrame(oge_rows)

In [6]:
df_oge_final.head()

,dataset_source,task_id,question,problem,question_raw,problem_raw,answer_options,answer
0,oge_fipi,45B944,Какое из следующих утверждений является истинн...,Какое из следующих утверждений является истинн...,Какое из следующих утверждений является истинн...,Какое из следующих утверждений является истинн...,[1) Площадь квадрата равна произведению двух е...,NaN
1,oge_fipi,426640,Какое из следующих утверждений является истинн...,Какое из следующих утверждений является истинн...,Какое из следующих утверждений является истинн...,Какое из следующих утверждений является истинн...,"[1) Все углы ромба равны., 2) Если стороны одн...",NaN
2,oge_fipi,494C47,Мощность постоянного тока (в ваттах) вычисляет...,Мощность постоянного тока (в ваттах) вычисляет...,Мощность постоянного тока (в ваттах) вычисляет...,Мощность постоянного тока (в ваттах) вычисляет...,[],NaN
3,oge_fipi,46334D,"У бабушки 20 чашек: 10 с красными цветами, ост...","У бабушки 20 чашек: 10 с красными цветами, ост...","У бабушки 20 чашек: 10 с красными цветами, ост...","У бабушки 20 чашек: 10 с красными цветами, ост...",[],NaN
4,oge_fipi,4F5745,Один из углов прямоугольной трапеции равен 64 ...,Один из углов прямоугольной трапеции равен 64 ...,Один из углов прямоугольной трапеции равен 64 ...,Один из углов прямоугольной трапеции равен 64 ...,[],NaN

In [7]:
common_columns = sorted(set(df_all.columns) | set(df_oge_final.columns))

df_all = df_all.reindex(columns=common_columns)
df_oge_final = df_oge_final.reindex(columns=common_columns)

df_all = pd.concat([df_all, df_oge_final], ignore_index=True)

In [8]:
df_all.head()

,answer,answer_options,answer_type,codifier,dataset_source,problem,problem_raw,problem_text,question,question_raw,question_text,task_id,task_number,variant_id,variant_title,variant_url,year_block
0,29,NaN,Краткий ответ,['7.5 Координаты и векторы'],fipi,NaN,"<p class=""MsoNormal"">Даны векторы <span class=...",Даны векторы \overrightarrow{a} ( 25; 0 ) и \o...,NaN,Даны векторы a &#x2192; ( 25;&#x2009;0 ) и b ...,Даны векторы a → ( 25; 0 ) и b → ( 1; −5 ). На...,40B442,2.0,NaN,NaN,NaN,NaN
1,-6,NaN,Краткий ответ,"['2.1 Целые и дробно-рациональные уравнения', ...",fipi,NaN,"<p class=""MsoNormal"">Найдите корень уравнения ...",Найдите корень уравнения ( 1 7 ) x + 4 = 49 .,NaN,Найдите корень уравнения ( 1 7 ) x&#x2009;+&#x...,Найдите корень уравнения ( 1 7 ) x + 4 =49 .; ;,4CBD4E,6.0,NaN,NaN,NaN,NaN
2,NaN,NaN,Развёрнутый ответ,"['2.3 Тригонометрические уравнения', '2.4 Пока...",fipi,NaN,"<p class=""MsoNormal"">а) Решите уравнение <m:ma...",а) Решите уравнение 9 sin 2 x − 3 2 2 sin x 11...,NaN,а) Решите уравнение 9 sin2x &#x2212; 3 2 2 sin...,а) Решите уравнение 9 sin2x − 3 2 2 sinx 11sin...,FDA042,13.0,NaN,NaN,NaN,NaN
3,82,NaN,Краткий ответ,['7.5 Координаты и векторы'],fipi,NaN,"<p class=""MsoNormal"">Даны векторы <m:math> <m:...",Даны векторы a → ( − 13 ; 4 ) и b → ( − 6 ; 1 ...,NaN,Даны векторы a &#x2192; ( &#x2212;&#x2009;13&#...,Даны векторы a → ( − 13 ; 4 ) и b → ( − 6 ; 1 ...,0A394E,2.0,NaN,NaN,NaN,NaN
4,0.92,NaN,Краткий ответ,['6.2 Вероятность'],fipi,NaN,"<p class=""MsoNormal""><span>Фабрика выпускает с...",Фабрика выпускает сумки. В среднем 4 сумки из ...,NaN,Фабрика выпускает сумки. В среднем 4 сумки из ...,Фабрика выпускает сумки. В среднем 4 сумки из ...,75244F,4.0,NaN,NaN,NaN,NaN

In [9]:
df_all.to_csv('tasks_with_oge.csv', index=False)

In [ ]:


def extract_year(title):
    if not title:
        return None
    m = re.search(r'\d{2}\.\d{2}\.(\d{4})', title)
    if m:
        return int(m.group(1))
    m = re.search(r'[Nn]?(\d{4})', title)
    if m:
        return int(m.group(1))
    return None

rows = []

files = {
    'result1.json': 'shkolkovo_fipi',
    'result2.json': 'shkolkovo_fipi',
    'result3.json': 'shkolkovo_fipi',
    'result4.json': 'shkolkovo_author',
}

for filename, source in files.items():
    with open(filename) as f:
        data = json.load(f)

    for variant in data:
        if 'error' in variant or 'questions' not in variant:
            continue

        url        = variant.get('url')
        title      = variant.get('title')
        year_block = extract_year(title)

        for q in variant['questions']:
            text = q.get('text')
            rows.append({
                'dataset_source': source,
                'task_id':        q.get('exercise_id'),
                'task_number':    q.get('number'),
                'question':       text,
                'problem':        text,
                'question_raw':   text,
                'problem_raw':    text,
                'answer':         q.get('answer'),
                'solution':       q.get('solution'),
                'answer_options': None,
                'variant_url':    url,
                'variant_title':  title,
                'year_block':     year_block,
            })

df_new = pd.DataFrame(rows)
print(f'Новых строк: {len(df_new)}')
print(df_new['dataset_source'].value_counts())


df_main = pd.read_csv('tasks_with_oge.csv')
print(f'\nОсновной датасет: {len(df_main)} строк')

df_merged = pd.concat([df_main, df_new], ignore_index=True, sort=False)
print(f'Итого после склейки: {len(df_merged)} строк')
print(df_merged['dataset_source'].value_counts())


df_merged.to_csv('tasks_merged.csv', index=False)
print('\nСохранено в tasks_merged.csv')